#!/bin/bash
cred_count = `mysql -u root -pnova -s -s -e "use keystone; select count(C.key) from credentials C join users U where C.user_id=U.id and U.name='test'"` 
if [ -z $cred_count ]
then
	echo zero_results
else
	echo some_results
fi
